// <auto-generated />
namespace RestaurantPlanner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class corrected_references : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(corrected_references));
        
        string IMigrationMetadata.Id
        {
            get { return "201711161822547_corrected_references"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
